# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 23:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('found_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'time found')),
                ('found_desc', models.CharField(default=0, max_length=500)),
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('found_location', models.CharField(default=b'Duke Campus', max_length=300)),
                ('posted_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'time published')),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('lost_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'time lost')),
                ('lost_desc', models.CharField(default=0, max_length=500)),
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('lost_location', models.CharField(default=b'Duke Campus', max_length=300)),
                ('posted_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'date published')),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'anonymous', max_length=300)),
                ('email', models.CharField(default=0, max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lostitem',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Reporter'),
        ),
        migrations.AddField(
            model_name='founditem',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Reporter'),
        ),
    ]
