# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170326_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='image',
            field=models.CharField(default=b'', max_length=5000000),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.CharField(default=b'', max_length=5000000),
        ),
    ]
