# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170327_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founditems', to='app.Reporter'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lostitems', to='app.Reporter'),
        ),
    ]
